# Generated by Django 5.0.7 on 2024-07-24 13:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="text",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
